name: agro_smart_tech
description: Voice-first Urdu AI Farming Assistant
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Voice & AI
  flutter_tts: ^4.2.3
  speech_to_text: ^7.3.0
  permission_handler: ^12.0.1
  http: ^1.6.0

  # UI & Animations
  confetti: ^0.8.0
  connectivity_plus: ^7.0.0

  # Offline Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Image & ML
  image_picker: ^1.2.1
  tflite_flutter: ^0.12.1
  camera: ^0.11.3
  image: ^4.5.4

  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/icons/icon.png
    - assets/images/
    - assets/images/Voice Q&A in Urdu.jpg
    - assets/images/AI Crop Disease Detection.jpg
    - assets/images/Real-Time Mandi Rates.png
    - assets/images/Digital Farmer Marketplace.jpg
    - assets/images/Accurate Weather Forecast.jpg
    - assets/images/Works Offline.webp
    - assets/models/plant_disease_model.tflite
    - assets/models/labels.txt

  fonts:
    - family: NotoNastaliq
      fonts:
        - asset: assets/fonts/NotoNastaliqUrdu-Regular.ttf

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  remove_alpha_ios: true